"""Add file_type and extracted_text to uploads

Revision ID: 01a14f18d50b
Revises: c5b8217bcf34
Create Date: 2025-05-01 03:05:19.745990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a14f18d50b'
down_revision = 'c5b8217bcf34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
