"""Update Upload table structure

Revision ID: c5b8217bcf34
Revises: 9d5f36c62666
Create Date: 2025-05-01 03:01:20.386909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5b8217bcf34'
down_revision = '9d5f36c62666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('uploads', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('uploads', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('uploads', 'upload_time')
    op.drop_column('uploads', 'file_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('uploads', sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('uploads', 'created_at')
    op.drop_column('uploads', 'extracted_text')
    op.drop_column('uploads', 'filename')
    # ### end Alembic commands ###
