"""Verify schema sync

Revision ID: dab8b9113221
Revises: 7f10313e0459
Create Date: 2025-05-16 18:13:29.755464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab8b9113221'
down_revision = '7f10313e0459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('upload_path', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.Column('face_count', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('detection_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masking_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.Column('masked_file_path', sa.Text(), nullable=True),
    sa.Column('masking_method', sa.JSON(), nullable=True),
    sa.Column('masking_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ocr_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dlp_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ocr_result_id', sa.UUID(), nullable=True),
    sa.Column('info_type', sa.String(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('likelihood', sa.String(), nullable=True),
    sa.Column('original_text', sa.String(), nullable=True),
    sa.Column('masked_text', sa.String(), nullable=True),
    sa.Column('position_start', sa.String(), nullable=True),
    sa.Column('position_end', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ocr_result_id'], ['ocr_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face_regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('face_detection_id', sa.UUID(), nullable=True),
    sa.Column('x', sa.String(), nullable=True),
    sa.Column('y', sa.String(), nullable=True),
    sa.Column('width', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['face_detection_id'], ['face_detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_regions')
    op.drop_table('dlp_results')
    op.drop_table('ocr_results')
    op.drop_table('masking_results')
    op.drop_table('logs')
    op.drop_table('face_detections')
    op.drop_table('uploads')
    # ### end Alembic commands ###
